// vbclient.cpp
#import "VBComponent.dll" no_namespace
#include <iostream.h>
#include "Component\component.h"	// Generated by MIDL for ISum definition

void main()
{
	int result;

	CoInitialize(NULL);
	_COM_SMARTPTR_TYPEDEF(ISum, __uuidof(ISum));
	ISumPtr myRef(__uuidof(VBInsideDCOM));
	myRef->Sum(5, 13, &result);
	cout << "5 + 13 = " << result << endl;
	myRef = NULL;
	CoUninitialize();
}