//*******************************************************************
//** Include the specification of the IUnknown interface
//*******************************************************************
import "unknwn.idl";

//*******************************************************************
//**  Interface for IHello
//*******************************************************************
[ object, uuid(11111111-1111-1111-1111-111111111111) ]
interface IHello : IUnknown
{
    HRESULT SayHello();
}

